### ISSUE TITLE
Dexter never finishes running on Windows Chrome Error

### ISSUE THREAD

**Issue by kschne7** [Appdynamics/AppDynamics.DEXTER#118]
2020-08-28 01:02:18.2061|Info|AppDynamics.Dexter|6012|1|AppDynamics.Dexter.Console|Trying to open Chrome Web Driver from D:\DEXTER2\core-win\ChromeDriver\83
2020-08-28 01:02:20.1390|Warn|AppDynamics.Dexter|6012|1|AppDynamics.Dexter.Console|OpenQA.Selenium.WebDriverException: unknown error: cannot find Chrome binary
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
   at AppDynamics.Dexter.ProcessingSteps.ExtractAPMEntityDashboardScreenshots.Execute(ProgramOptions programOptions, JobConfiguration jobConfiguration) in C:\appdynamics\AppDynamics.DEXTER\src\ProcessingSteps\Extract\ExtractAPMEntityDashboardScreenshots.cs:line 192
2020-08-28 01:02:20.1390|Trace|AppDynamics.Dexter|6012|1|AppDynamics.Dexter.Console|ExtractAPMEntityDashboardScreenshots(42): [1/388], https://discoverfinancial.saas.appdynamics.com Account_Center_Decision_Engine duration 00:00:02.1128286 (2112 ms)
2020-08-28 01:02:20.1522|Trace|AppDynamics.Dexter|6012|1|AppDynamics.Dexter.Console|ExtractAPMEntityDashboardScreenshots(42): total duration 00:00:02.1282348 (2128 ms)
2020-08-28 01:02:20.1677|Warn|AppDynamics.Dexter|6012|1|AppDynamics.Dexter.Console|If you need support, please review https://github.com/Appdynamics/AppDynamics.DEXTER/wiki#getting-support and send the logs
2020-08-28 01:02:20.1677|Trace|AppDynamics.Dexter|6012|1|AppDynamics.Dexter.Console|Application execution took 2.08:09:10.4694748 (202150469 ms)

**Comment by kschne7** [comment]
I fixed this by installing Chrome 32 bit
