### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by kschne7** [Appdynamics/AppDynamics.DEXTER#119]
2020-09-17 13:05:47.4165|Info|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|Executing job step IndexBIQMetrics(85)
2020-09-17 13:05:47.4165|Trace|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|IndexBIQMetrics(85): Starting
2020-09-17 13:05:47.4165|Trace|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|LicensedReports.EntityMetrics=True
2020-09-17 13:05:47.4165|Trace|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|Input.Metrics=True
2020-09-17 13:05:47.4165|Warn|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|No BIQ targets to process
2020-09-17 13:05:47.4165|Trace|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|IndexBIQMetrics(85): total duration 00:00:00.0015382 (1 ms)
2020-09-17 13:05:47.4310|Info|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|Executing job step IndexAPMMetricsList(86)
2020-09-17 13:05:47.5366|Trace|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|IndexAPMMetricsList(86): Starting
2020-09-17 13:05:47.5366|Trace|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|LicensedReports.EntityMetrics=True
2020-09-17 13:05:47.5366|Trace|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|Input.MetricsList=True
2020-09-17 13:05:47.5366|Info|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|IndexAPMMetricsList(86): [1/394], https://discoverfinancial.saas.appdynamics.com APPNAME(xxx) [APM]
2020-09-17 13:05:47.8322|Warn|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|System.ArgumentException: An item with the same key has already been added. Key: Oracle DB-LDAP-Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at AppDynamics.Dexter.ProcessingSteps.IndexAPMMetricsList.Execute(ProgramOptions programOptions, JobConfiguration jobConfiguration) in C:\appdynamics\AppDynamics.DEXTER\src\ProcessingSteps\Index\IndexAPMMetricsList.cs:line 110
2020-09-17 13:05:47.8414|Trace|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|IndexAPMMetricsList(86): [1/394], https://discoverfinancial.saas.appdynamics.com Account_Center_Decision_Engine duration 00:00:00.3027369 (302 ms)
2020-09-17 13:05:47.8414|Trace|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|IndexAPMMetricsList(86): total duration 00:00:00.3167905 (316 ms)
2020-09-17 13:05:47.8542|Warn|AppDynamics.Dexter|8500|1|AppDynamics.Dexter.Console|If you need support, please review https://github.com/Appdynamics/AppDynamics.DEXTER/wiki#getting-support and send the logs

**Comment by bhjelmar** [comment]
Hey @kschne7 this is likely a duplicate of [114](https://github.com/Appdynamics/AppDynamics.DEXTER/issues/114).
Can you please download our [latest release](https://github.com/Appdynamics/AppDynamics.DEXTER/releases/tag/20.8.1.0) and verify it works for you?

**Comment by kschne7** [comment]
2020-10-02 00:04:32.0921|Warn|AppDynamics.Dexter|4924|1|AppDynamics.Dexter.Console|System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at AppDynamics.Dexter.ProcessingSteps.IndexAPMMetricsList.Execute(ProgramOptions programOptions, JobConfiguration jobConfiguration) in C:\Users\bhjel\RiderProjects\AppDynamics.DEXTER\ProcessingSteps\Index\IndexAPMMetricsList.cs:line 855
2020-10-02 00:04:32.1040|Trace|AppDynamics.Dexter|4924|1|AppDynamics.Dexter.Console|IndexAPMMetricsList(86): [4/411], https://discoverfinancial.saas.appdynamics.com Acquisitions duration 00:00:26.8645941 (26864 ms)
2020-10-02 00:04:32.1040|Trace|AppDynamics.Dexter|4924|1|AppDynamics.Dexter.Console|IndexAPMMetricsList(86): total duration 00:00:43.2669704 (43266 ms)
2020-10-02 00:04:32.1284|Warn|AppDynamics.Dexter|4924|1|AppDynamics.Dexter.Console|If you need support, please review https://github.com/Appdynamics/AppDynamics.DEXTER/wiki#getting-support and send the logs
2020-10-02 00:04:32.1546|Trace|AppDynamics.Dexter|4924|1|AppDynamics.Dexter.Console|Application execution took 1.05:18:28.5150149 (105508515 ms)

**Comment by kschne7** [comment]
We have a very large controller - this runs for over 26 hours -

**Comment by danielodievich** [comment]
You can always restart the job https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Restart-Job-From-Specific-Step at the https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Phases-and-Job-Steps#indexapmmetrics-80 step and not rerun previous 25.99 hours.

Daniel

**Comment by bhjelmar** [comment]
Please try with latest release, this issue should be fixed in version 21.6.0.0.
