### ISSUE TITLE
Dexter seems to fail when loading a customer application (UWM,   MuleSoft Application)

### ISSUE THREAD

**Issue by bhomrich** [Appdynamics/AppDynamics.DEXTER#128]
**Describe the bug**
While doing a SaaS controller migration planning exercise for United Wholesale Mortgage,   we took configuration and metadata dumps for a non-production and production controller.

Non-production DEXTER extracts worked without issue
Production repeatedly failed,  stopping in the middle of dumping an app in the middle of their applications at an app called "Mulesoft".   

Dexter throws and error,  then stops processing,  and stops generating CSV files.

We have extracted the application configuration using ConfigExporter,  hoping that the problem will replicate in another controller after loading.   (JSON attached)

**To Reproduce**
1. Load this Mulesoft.JSON
2. Adapt the UnitedShoreJob file to fit your controller
3. Run the DEXTER job to attempt to load Mulesoft

**Expected behavior**
DEXTER stops generating output files and cancels remaining job steps including report generation.

**Screenshots**

**Desktop (please complete the following information):**
 - .NET Framework Type (Full/Core)
 - .NET/.NET Core Framework Version 

**Logs**
Add logs from the program execution https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Log-Files

**Reports**
Include any produced reports that you have issues with

**Comment by bhomrich** [comment]
[MuleSoft.json.txt](https://github.com/Appdynamics/AppDynamics.DEXTER/files/5568431/MuleSoft.json.txt)

and a fragment of a ConsoleLog showing the failure happening and stopping the run.
```

2020-11-04 11:21:01.8938|Trace|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|IndexAPMMetricsList(86): [46/108], https://appd.uwm.com MISMO duration 00:00:00.3813606 (381 ms)
2020-11-04 11:21:01.9084|Info|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|IndexAPMMetricsList(86): [47/108], https://appd.uwm.com MuleSoft(37) [APM]
2020-11-04 11:21:01.9515|Info|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Parse metrics
2020-11-04 11:21:01.9515|Info|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix INFRA with depth 14
2020-11-04 11:21:01.9978|Trace|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix INFRA with depth 14 produced 7948 metrics
2020-11-04 11:21:01.9978|Info|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix APP with depth 12
2020-11-04 11:21:01.9978|Trace|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix APP with depth 12 produced 1478 metrics
2020-11-04 11:21:01.9978|Info|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix BACKEND with depth 6
2020-11-04 11:21:01.9978|Trace|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix BACKEND with depth 6 produced 3 metrics
2020-11-04 11:21:01.9978|Info|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix BT with depth 22
2020-11-04 11:21:02.0760|Trace|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix BT with depth 22 produced 5548 metrics
2020-11-04 11:21:02.0760|Info|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix SEP with depth 5
2020-11-04 11:21:02.0760|Trace|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix SEP with depth 5 produced 300 metrics
2020-11-04 11:21:02.0760|Info|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix ERR with depth 7
2020-11-04 11:21:02.1026|Trace|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix ERR with depth 7 produced 1240 metrics
2020-11-04 11:21:02.1026|Info|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix IP with depth 6
2020-11-04 11:21:02.1070|Trace|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix IP with depth 6 produced 0 metrics
2020-11-04 11:21:02.1070|Info|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix WEB with depth 6
2020-11-04 11:21:02.1070|Trace|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix WEB with depth 6 produced 0 metrics
2020-11-04 11:21:02.1070|Info|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix MOBILE with depth 8
2020-11-04 11:21:02.1070|Trace|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Prefix MOBILE with depth 8 produced 0 metrics
2020-11-04 11:21:02.1244|Warn|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at AppDynamics.Dexter.ProcessingSteps.IndexAPMMetricsList.Execute(ProgramOptions programOptions, JobConfiguration jobConfiguration) in C:\Users\bhjel\RiderProjects\AppDynamics.DEXTER\ProcessingSteps\Index\IndexAPMMetricsList.cs:line 855
2020-11-04 11:21:02.1244|Trace|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|IndexAPMMetricsList(86): [47/108], https://appd.uwm.com MuleSoft duration 00:00:00.2201920 (220 ms)
2020-11-04 11:21:02.1443|Trace|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|IndexAPMMetricsList(86): total duration 00:03:15.5740044 (195574 ms)
2020-11-04 11:21:02.1581|Warn|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|If you need support, please review https://github.com/Appdynamics/AppDynamics.DEXTER/wiki#getting-support and send the logs
2020-11-04 11:21:02.1581|Trace|AppDynamics.Dexter|2964|1|AppDynamics.Dexter.Console|Application execution took 03:18:44.6211793 (11924621 ms)
```

**Comment by bhomrich** [comment]
In hindsight,  the customer application configuration may contain sensitive info.   Sending it straight to AppD (BradH) for debugging support.

**Comment by sfc-gh-dodievich** [comment]
I thought @bradhjelmar fixed that already. This is for the metrics lookup when something in the entity name is null.
