### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'key')

### ISSUE THREAD

**Issue by mikeylee** [Appdynamics/AppDynamics.DEXTER#130]
**Describe the bug**
I recently downloaded full-win-20.8.1.0, and running DEXTER against Saas AppD Controller, it detects I have 20.8.0.0 and prompts accordingly:
"Latest released version is 20.8.1.0, and yours is 20.8.0.0. Would you like to upgrade (y/n)?".  So how do I get a copy of 20.8.1.0 ?

Also, when running Jobfile with Target.Type="APM" I get the following error:

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at AppDynamics.Dexter.ProcessingSteps.IndexAPMMetricsList.Execute(ProgramOptions programOptions, JobConfiguration jobConfiguration) in C:\Users\bhjel\RiderProjects\AppDynamics.DEXTER\ProcessingSteps\Index\IndexAPMMetricsList.cs:line 855

How do I address this error?

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - .NET Framework Type (Full/Core)
 - .NET/.NET Core Framework Version 

**Logs**
Add logs from the program execution https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Log-Files

**Reports**
Include any produced reports that you have issues with

**Comment by willispin** [comment]
I have the same issue. I have tired multiple versions. I am getting the same error message and I am not able to run a report.

**Comment by bhjelmar** [comment]
Please try with latest release, this issue should be fixed in version 21.6.0.0.
