### ISSUE TITLE
ExtractAPMEntityDashboardScreenshots failed with System.ComponentModel.Win32Exception

### ISSUE THREAD

**Issue by davidskeen** [Appdynamics/AppDynamics.DEXTER#89]
Downloaded 1.2.45.0 for osx-core to run on macOS 10.15.1 (Catalina)
Ran xattr -d com.apple.quarantine AppDynamics.DEXTER.1.2.45.0-osx-core.zip
Copied DefaultJob.json and used all of these values for the job for one (large) app
Invoked ./AppDynamics.Dexter -j ~/Google\ Drive/Tools/DEXTER/prod-1205-0700.json  -o ~/Documents/Tools/DEXTEROut/
The job ended with this output. I'll drop the dashboard part of the report for now, not sure what perms needed to invoke the chromedriver; if I chmod it 755 would that suffice?
[logs.zip](https://github.com/Appdynamics/AppDynamics.DEXTER/files/3928362/logs.zip)

ExtractAPMEntityDashboardScreenshots(32): Starting
Input.EntityDashboards=True
ExtractAPMEntityDashboardScreenshots(32): [1/1], https://siteone.saas.appdynamics.com Unity Enterprise(3105) [APM]
Trying to open Chrome Web Driver from /Users/dskeen/Google Drive/Tools/DEXTER/AppDynamics.DEXTER.1.2.45.0-osx-core/core-osx/ChromeDriver/78
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at OpenQA.Selenium.DriverService.Start()
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
   at AppDynamics.Dexter.ProcessingSteps.ExtractAPMEntityDashboardScreenshots.Execute(ProgramOptions programOptions, JobConfiguration jobConfiguration) in C:\appdynamics\AppDynamics.DEXTER\src\ProcessingSteps\Extract\ExtractAPMEntityDashboardScreenshots.cs:line 179
ExtractAPMEntityDashboardScreenshots(32): [1/1], https://siteone.saas.appdynamics.com Unity Enterprise duration 00:00:00.5873023 (587 ms)
ExtractAPMEntityDashboardScreenshots(32): total duration 00:00:00.5948291 (594 ms)
If you need support, please review https://github.com/Appdynamics/AppDynamics.DEXTER/wiki#getting-support and send the logs
Application execution took 00:48:47.5013999 (2927501 ms)
DSKEEN-M-841M:Google Drive/Tools/DEXTER/AppDynamics.DEXTER.1.2.45.0-osx-core/core-osx>

**Comment by davidskeen** [comment]
[logs.zip](https://github.com/Appdynamics/AppDynamics.DEXTER/files/3928364/logs.zip)

**Comment by danielodievich** [comment]
You already ran the xattr command, that should have made the thing unstarted.
Can you run the executable from /Users/dskeen/Google Drive/Tools/DEXTER/AppDynamics.DEXTER.1.2.45.0-osx-core/core-osx/ChromeDriver/78 yourself and see what happens?

**Comment by davidskeen** [comment]
To run it from the command line I have to chmod the file. Should re-run the dashboard report with these file perms?

DSKEEN-M-841M:Google Drive/Tools/DEXTER/AppDynamics.DEXTER.1.2.45.0-osx-core/core-osx/ChromeDriver/78/mac64> ./chromedriver
-bash: ./chromedriver: Permission denied
DSKEEN-M-841M:Google Drive/Tools/DEXTER/AppDynamics.DEXTER.1.2.45.0-osx-core/core-osx/ChromeDriver/78/mac64> chmod +x chromedriver 
DSKEEN-M-841M:Google Drive/Tools/DEXTER/AppDynamics.DEXTER.1.2.45.0-osx-core/core-osx/ChromeDriver/78/mac64> ./chromedriver
Starting ChromeDriver 78.0.3904.11 (eaaae9de6b8999773fa33f92ce1e1bbe294437cf-refs/branch-heads/3904@{#86}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1575571661.641][WARNING]: FromSockAddr failed on netmask
^C
DSKEEN-M-841M:Google Drive/Tools/DEXTER/AppDynamics.DEXTER.1.2.45.0-osx-core/core-osx/ChromeDriver/78/mac64>

**Comment by danielodievich** [comment]
Yes, please, adjust the Status parameter https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Restart-Job-From-Specific-Step with https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Phases-and-Job-Steps#extractapmentitydashboardscreenshots-32 and restart

**Comment by davidskeen** [comment]
I hit the same problem with appdynamics.dexter.1.2.46.0-osx-core/core-osx/ChromeDriver/80/mac64/chromedriver. I set perms to 755 and restarted the same job. This time I hit a new problem with chromedriver:

ExtractAPMEntityDashboardScreenshots(32): Starting
Input.EntityDashboards=True
ExtractAPMEntityDashboardScreenshots(32): [1/1], https://siteone.saas.appdynamics.com Unity Enterprise(3105) [APM]
Trying to open Chrome Web Driver from /Users/dskeen/Documents/Tools/DEXTER/appdynamics.dexter.1.2.46.0-osx-core/core-osx/ChromeDriver/80
Starting ChromeDriver 80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}) on port 60587
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1578081284.960][WARNING]: FromSockAddr failed on netmask
Unable to create Web Driver from /Users/dskeen/Documents/Tools/DEXTER/appdynamics.dexter.1.2.46.0-osx-core/core-osx/ChromeDriver/80/mac64
Trying to open Chrome Web Driver from /Users/dskeen/Documents/Tools/DEXTER/appdynamics.dexter.1.2.46.0-osx-core/core-osx/ChromeDriver/79
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at OpenQA.Selenium.DriverService.Start()
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
   at AppDynamics.Dexter.ProcessingSteps.ExtractAPMEntityDashboardScreenshots.Execute(ProgramOptions programOptions, JobConfiguration jobConfiguration) in C:\appdynamics\AppDynamics.DEXTER\src\ProcessingSteps\Extract\ExtractAPMEntityDashboardScreenshots.cs:line 179
ExtractAPMEntityDashboardScreenshots(32): [1/1], https://siteone.saas.appdynamics.com Unity Enterprise duration 00:00:00.8221364 (822 ms)
ExtractAPMEntityDashboardScreenshots(32): total duration 00:00:00.8297320 (829 ms)
If you need support, please review https://github.com/Appdynamics/AppDynamics.DEXTER/wiki#getting-support and send the logs
Application execution took 00:03:53.4257994 (233425 ms)

When I invoke chromedriver by itself:
DSKEEN-M-841M:Documents/Tools/DEXTER/appdynamics.dexter.1.2.46.0-osx-core/core-osx/ChromeDriver/80/mac64> ./chromedriver 
Starting ChromeDriver 80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1578081394.327][WARNING]: FromSockAddr failed on netmask
^C

I will leave this job where it is if you can figure out a workaround.

**Comment by danielodievich** [comment]
Fixed in https://github.com/Appdynamics/AppDynamics.DEXTER/releases/tag/1.2.47.0
