### ISSUE TITLE
System.InvalidOperationException: The license has expired. 

### ISSUE THREAD

**Issue by kaidong-chr** [Appdynamics/AppDynamics.DEXTER#91]
AppDynamics DEXTER Version 1.2.45.0

Ran \core-win\AppDynamics.Dexter.exe --job-file BlackFriday.json 

The report completed with the following:

System.InvalidOperationException: The license has expired.
   at ?.(Object )
   at ?.(Object )
   at ?.  (? ,   )
   at ?.()
   at ?.(Boolean )
   at ?.(Object )
   at ?.(Object )
   at ?.()
   at ?.?(? ,   )
   at ?.()
   at ?.(Boolean )
   at ?.(Object )
   at ?.(Object )
   at ?.()
   at ?.(Object , UInt32 )
   at ?.(Boolean )
   at ?.(Boolean )
   at ?.(Object[] , Type[] , Type[] , Object[])
   at ?.(Int32 , Type[] , Type[] , Boolean)
   at ?.  (? ,   )
   at ?.()
   at ?.(Boolean )
   at ?.(Object )
   at ?.(Object )
   at ?.()
   at ?.(Object , UInt32 )
   at ?.(Boolean )
   at ?.(Object[] , Type[] , Type[] , Object[])
   at ?.(Stream , String , Object[] , Type[], Type[] , Object[] )
   at Aspose.Words.License.SetLicense(String licenseName)
   at AppDynamics.Dexter.ProcessingSteps.ReportAPMApplicationSummary.Execute(ProgramOptions programOptions, JobConfiguration jobConfiguration) in C:\appdynamics\AppDynamics.DEXTER\src\ProcessingSteps\Report\ReportAPMApplicationSummary.cs:line 55
   at AppDynamics.Dexter.JobStepRouter.ExecuteJobThroughSteps(ProgramOptions programOptions) in C:\appdynamics\AppDynamics.DEXTER\src\ProcessingSteps\JobStepRouter.cs:line 189
   at AppDynamics.Dexter.Program.RunProgramETL(ProgramOptions programOptions) in C:\appdynamics\AppDynamics.DEXTER\src\Program.cs:line 1037
   at AppDynamics.Dexter.Program.RunProgram(ProgramOptions programOptions) in C:\appdynamics\AppDynamics.DEXTER\src\Program.cs:line 74
   at AppDynamics.Dexter.Program.<>c.<Main>b__2_0(ProgramOptions programOptions) in C:\appdynamics\AppDynamics.DEXTER\src\Program.cs:line 44
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at AppDynamics.Dexter.Program.Main(String[] args) in C:\appdynamics\AppDynamics.DEXTER\src\Program.cs:line 42
Application execution took 00:00:11.9985934 (11998 ms)

It looks like the Apose.Word license expired on 20191124

https://github.com/Appdynamics/AppDynamics.DEXTER/blob/7f500bcc9f0895abaca38a81db54c1fc3964432b/Aspose.Words.lic#L16

The json I ran is a modified DefaultJob.json, is there something I can modify i the output to get around the expired word license?

**Comment by danielodievich** [comment]
Yes. Turn off the report by setting Output\ApplicationSummary=false in the jobparameters.json as described in https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Restart-Job-From-Specific-Step and restart the process from the place you want. But this is a second to last step so you are not missing much. You can restart from step 150
