### ISSUE TITLE
Selenium Web Driver exception.

### ISSUE THREAD

**Issue by Sravan921** [Appdynamics/AppDynamics.DEXTER#93]
OpenQA.Selenium.WebDriverException: unknown error: Chrome failed to start: exited normally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
   at AppDynamics.Dexter.ProcessingSteps.ExtractAPMEntityDashboardScreenshots.Execute(ProgramOptions programOptions, JobConfiguration jobConfiguration) in C:\appdynamics\AppDynamics.DEXTER\src\ProcessingSteps\Extract\ExtractAPMEntityDashboardScreenshots.cs:line 179

In the "Report" folder I only see StepDurations.csv

**Comment by danielodievich** [comment]
What OS are you running?
What version of Chrome is installed on your OS?
Can you upload logs, please?

**Comment by Sravan921** [comment]
[logs.zip](https://github.com/Appdynamics/AppDynamics.DEXTER/files/4167303/logs.zip)

Hi, PFA logs.

**Comment by Sravan921** [comment]
ExtractAPMEntityDashboardScreenshots(32): [1/404], https://appd.metlife.com 10103_MPM_DR(632) [APM]
Trying to find Chrome version on Windows in C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Chrome version is 79.0.3945.130
Trying to open Chrome Web Driver from C:\Users\ssukhavasi\Downloads\Dexter\core-win\ChromeDriver\80
Starting ChromeDriver 80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}) on port 61708
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
OpenQA.Selenium.WebDriverException: unknown error: Chrome failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
   at AppDynamics.Dexter.ProcessingSteps.ExtractAPMEntityDashboardScreenshots.Execute(ProgramOptions programOptions, JobConfiguration jobConfiguration) in C:\appdynamics\AppDynamics.DEXTER\src\ProcessingSteps\Extract\ExtractAPMEntityDashboardScreenshots.cs:line 179
ExtractAPMEntityDashboardScreenshots(32): [1/404], https://appd.metlife.com 10103_MPM_DR duration 00:00:01.3317963 (1331 ms)
ExtractAPMEntityDashboardScreenshots(32): total duration 00:00:01.3578361 (1357 ms)
If you need support, please review https://github.com/Appdynamics/AppDynamics.DEXTER/wiki#getting-support and send the logs
Application execution took 03:13:17.3935476 (11597393 ms)

**Comment by danielodievich** [comment]
Related https://bugs.chromium.org/p/chromedriver/issues/detail?id=2473 and https://github.com/SeleniumHQ/selenium/issues/6049

**Comment by Sravan921** [comment]
Windows OS
Chrome: Version 80.0.3987.87

Got the same exact error again even with a fresh install.

ExtractAPMEntityDashboardScreenshots(32): [1/1141], https://appd.metlife.com 10103_MPM_DR(632) [APM]
Trying to find Chrome version on Windows in C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Chrome version is 80.0.3987.87
Trying to open Chrome Web Driver from C:\Users\ssukhavasi\Downloads\AppDynamics.DEXTER.1.2.46.0-win-core\core-win\ChromeDriver\80
Starting ChromeDriver 80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}) on port 58549
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
OpenQA.Selenium.WebDriverException: unknown error: Chrome failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
   at AppDynamics.Dexter.ProcessingSteps.ExtractAPMEntityDashboardScreenshots.Execute(ProgramOptions programOptions, JobConfiguration jobConfiguration) in C:\appdynamics\AppDynamics.DEXTER\src\ProcessingSteps\Extract\ExtractAPMEntityDashboardScreenshots.cs:line 179
ExtractAPMEntityDashboardScreenshots(32): [1/1141], https://appd.metlife.com 10103_MPM_DR duration 00:00:02.2357498 (2235 ms)
ExtractAPMEntityDashboardScreenshots(32): total duration 00:00:02.2531931 (2253 ms)
If you need support, please review https://github.com/Appdynamics/AppDynamics.DEXTER/wiki#getting-support and send the logs
Application execution took 03:10:37.7258072 (11437725 ms)

**Comment by danielodievich** [comment]
Fixed in the https://github.com/Appdynamics/AppDynamics.DEXTER/releases/tag/1.2.47.0
